version: "3.5"

services:

  nginx:
    container_name: gitpab-nginx
    hostname: gitpab-nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - gitpab-code:/var/www/html:delegated
    ports:
      - "8888:80"
      - "8443:443"
    depends_on:
      - php
      - db
    networks:
      - panacea-network

  php:
    container_name: gitpab-php
    hostname: gitpab-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - gitpab-code:/var/www/html:delegated
    environment:
      GITLAB_PRIVATE_TOKEN: ${token}
      GITLAB_RESTRICTIONS_PROJECT_IDS: ${projects}
      GITLAB_HOST: ${host}
      APP_LOCALE: en
    ports:
      - "9999:9000"
    depends_on:
      - db
    networks:
      - panacea-network

  db:
    container_name: gitpab-db
    hostname: gitpab-db
    image: postgres
    volumes:
      - gitpab-pgsql:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: gitpab
      POSTGRES_USER: gitpab
      POSTGRES_PASSWORD: gitpab
    networks:
      - panacea-network

volumes:

  gitpab-pgsql: {}
  gitpab-code: {}

networks:

  panacea-network:
    name: panacea-network